# Generated by Django 5.2.8 on 2025-11-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_alter_variable_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
